name: certmanager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^4.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  url_launcher: ^6.2.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  firebase_core_platform_interface: 4.4.1
